"""rename_metadata_column

Revision ID: 78b3875b9dbe
Revises: 968c12650f13
Create Date: 2026-06-18 15:38:42.018234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78b3875b9dbe'
down_revision: Union[str, Sequence[str], None] = '968c12650f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('action_metadata', sa.JSON(), nullable=True))
    op.drop_column('audit_logs', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'action_metadata')
    # ### end Alembic commands ###
