"""Add course constraints

Revision ID: ff4c00d30c23
Revises: a67d843bb908
Create Date: 2026-06-06 17:24:18.880519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4c00d30c23'
down_revision: Union[str, Sequence[str], None] = 'a67d843bb908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_course_code', 'courses', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_course_code', 'courses', type_='unique')
    # ### end Alembic commands ###
